from text_extraction import *


file_name = input('File path: ')
temp_directory_name, text = parse_pdf(file_name)
special_words = extract_special_words(text)
print('Registry keys')
registry_keys = registry_keys_extract(special_words)
print(registry_keys)
special_words = clear_registry_keys(special_words)
hashes = extract_hashes(text, special_words=special_words)
print()
print('Hashes')
print(hashes)
print()
special_words = clear_hashes(special_words, hashes)
special_words = clear_special_words(special_words)
print('Special words')
print(special_words)
print()
names = extract_all_names(text)
extractor = CountryInfoExtract(names)
print('Countries')
countries = extractor.extract_countries()
print(countries)
print()
print('Cities')
cities = extractor.extract_cities()
print(cities)
print()
print('Country regions')
country_regions = extractor.extract_country_regions()
print(country_regions)
print()
print('Global regions')
global_regions = extractor.deeply_extract_global_region()
print(global_regions)
print()
print('MITRE ATT&CK techniques')
print(search_techniques(text))
files, extensions = extract_file_names(text)
print()
print('File names')
print(files)
print()
print('File extensions')
print(extensions)
domain_names = extract_domain_names(text)
print()
print('Domain names')
print(domain_names)
ip_addresses = extract_ip_addresses(text)
print()
print('Ip addresses')
print(ip_addresses)
providers = extract_providers(text)
print()
print('Providers')
print(providers)
protocols = extract_protocols(text)
print()
print('Protocols')
print(protocols)
images_text = extract_languages_from_images(temp_directory_name)
languages = get_languages(images_text)
print()
print('Program languages')
print(languages)
companies, software = extract_companies_software(names - cities - countries - country_regions)
print()
print('Companies')
print(companies)
print()
print('Software')
print(software)
