from text_extraction import parse_pdf, extract_all_names,\
    CountryInfoExtract, search_techniques, extract_file_names, extract_providers,\
    extract_hashes, extract_domain_names, extract_ip_addresses,\
    extract_languages_from_images, get_languages, extract_companies_software,\
    extract_protocols

file_name = 'APT27+turns+to+ransomware.pdf'
temp_directory_name, text = parse_pdf(file_name)
names = extract_all_names(text)
extractor = CountryInfoExtract(names)

print('Countries')
print(extractor.extract_countries())
print()
print('Cities')
print(extractor.extract_cities())
print()
print('Country regions')
print(extractor.extract_country_regions())
print()
print('Global regions')
print(extractor.deeply_extract_global_region())
print()
print('MITRE ATT&CK techniques')
print(search_techniques(text))
files, extensions = extract_file_names(text)
print()
print('File names')
print(files)
print()
print('File extensions')
print(extensions)
hashes = extract_hashes(text)
print()
print('Hashes')
print(hashes)
domain_names = extract_domain_names(text)
print()
print('Domain names')
print(domain_names)
ip_addresses = extract_ip_addresses(text)
print()
print('Ip addresses')
print(ip_addresses)
providers = extract_providers(text)
print()
print('Providers')
print(providers)
protocols = extract_protocols(text)
print()
print('Protocols')
print(protocols)
# companies, software = extract_companies_software(names)
# print()
# print('Companies')
# print(companies)
# print()
# print('Software')
# print(software)
images_text = extract_languages_from_images(temp_directory_name)
languages = get_languages(images_text)
print()
print('Program languages')
print(languages)

